//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Notes')
export class NotesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  NoteID: number;

  @Column('integer', { nullable: true })
  Denomination: number;

  @Column('integer', { nullable: true })
  Quantity: number;
}
