//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Payments')
export class PaymentsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  PaymentID: number;

  @Column('integer', { nullable: true })
  UserID: number;

  @Column('real', { nullable: true })
  Amount: number;

  @Column('text', { nullable: true })
  PaymentMethod: string;

  @Column('text', { nullable: true })
  TransactionID: string;

  @Column('date', { nullable: true })
  Timestamp: Date;
}
