//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Sellers')
export class SellersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  SellerID: number;

  @Column('text', { nullable: true })
  Name: string;

  @Column('text', { nullable: true })
  Notes: string;

  @Column('real', { nullable: true })
  Commission: number;
}
