//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="Loose Change Delivery App" />
    <CardContent>
      I want to create an app that provides loose change to users when they need
      it. For example, if someone needs 1000 rupees in change, the app will
      provide 100 notes of 10 rupees each. Users can also select other
      denominations like 200, 100, 50, or 20 rupee notes, and the app will
      deliver the change within 30-40 minutes. The app should have an online
      payment feature, allowing users to pay through UPI, credit/debit card, net
      banking, or wallet payment. We will charge users a 5% fee, but if they
      require new notes, the fee will be 10%. The app will have both buyers and
      sellers, where buyers can purchase notes and sellers can sell their new
      notes. Sellers will receive a 2% commission on the app for selling their
      notes.
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
